doc: document opts.skipCache for client.get
slashtags/web-relay pull request #32
Opened 2023-09-07 08:44 UTC by Nuhvi

2023-09-07 12:42 UTC, MiguelMedeiros requested changes

2023-09-07 12:42 UTC, MiguelMedeiros commented on types/lib/client/index.d.ts
> +    get id(): any;
Saw the `any` type here. Any reason for that? Might be better with a specific type if possible. Thoughts?

2023-09-07 12:42 UTC, MiguelMedeiros commented on types/lib/client/index.d.ts
> +        id: any;
Same thing here with type: `any`

2023-09-07 12:42 UTC, MiguelMedeiros commented on types/lib/client/index.d.ts
> +    get id(): any;
It also seams that this is not related to the scope of this PR. 
Maybe could be a good idea to move this code to another PR.

2023-09-10 00:03 UTC, MiguelMedeiros approved these changes
ACK

2023-09-11 06:04 UTC, rbndg commented
@Nuhvi can you pls resolve conflicts

2023-09-12 05:30 UTC, merged